version: '3.8'

services:
  shop_backend:
    image: shop_backend
    container_name: shop_backend
    restart: always
    volumes:
      - ${APP_BASE_DIR}:/code/
      - ${APP_BASE_DIR}/volumes/logs:/code/lib/logs/
      - ${APP_BASE_DIR}/volumes/media:/code/lib/media/
    env_file:
      - .env
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "2"
    entrypoint: python3 manage.py
    command: runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name : db
    restart: always
    environment:
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      -   db:/var/lib/postgresql/data

volumes:
  db:
    driver: local